[[section-kata-11]]
== 11. I'll Have the BLT / Ein Schinkensandwitch Bitte

Ein nationaler Sandwichladen möchte "Bestellen über das Internet" erlauben.

*    Anwender: Tausende, vielleicht eines Tages Millionen
*   Anforderungen:
**      Benutzer geben ihre Bestellung auf, erhalten dann eine Uhrzeit für die Abholung ihres Sandwichs und eine Wegbeschreibung zum Geschäft (die mit mehreren externen Kartendiensten mit Verkehrsinformationen integriert werden muss)
**      Wenn der Laden einen Lieferservice anbietet, wird der Fahrer mit dem Sandwich zum Nutzer geschickt
**      Unterstützng für Bestellung über mobile Endgeräte
**      Angebot von nationalen Tagesangeboten/Specials
**      Unterstützng für lokale Tagesangebote und Sonderaktionen
**      Zahlung online oder persönlich/bei der Lieferung oder Abholung akzeptieren
* Zusätzlicher Kontext:
**      Die Sandwich-Läden sind Franchisebetriebe, jeder mit einem anderen Eigentümer.
**      Die Muttergesellschaft plant in naher Zukunft eine Expansion nach Übersee.
**      Das Unternehmensziel ist es, billige Arbeitskräfte einzustellen, um den Gewinn zu maximieren.
